# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/miguellopez/Desktop/PROYECTS/PAGOS/ARENERO-RAMIRO/FRONTEND/views/QT_DESIGNS/designs/edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from BACKEND.CRUD.CRUD_users import calcChargingPrice
from BACKEND.CRUD.CRUD_local_storage import CrudLocalStorage
from FRONTEND import icons


class UiForm(object):
    formInstance = None
    userToEdit = None

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1170, 426)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1170, 426))
        Form.setMaximumSize(QtCore.QSize(1170, 426))
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: rgb(254, 194, 248);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.editLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editLabel.sizePolicy().hasHeightForWidth())
        self.editLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.editLabel.setFont(font)
        self.editLabel.setStyleSheet("color:#000000;")
        self.editLabel.setScaledContents(False)
        self.editLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.editLabel.setWordWrap(True)
        self.editLabel.setObjectName("editLabel")
        self.verticalLayout.addWidget(self.editLabel)
        self.searchRecordLayout = QtWidgets.QHBoxLayout()
        self.searchRecordLayout.setObjectName("searchRecordLayout")
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.searchRecordLayout.addWidget(self.line)
        self.verticalLayout.addLayout(self.searchRecordLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.bodyLayout = QtWidgets.QHBoxLayout()
        self.bodyLayout.setObjectName("bodyLayout")
        self.name_braceletNum_formLayout = QtWidgets.QFormLayout()
        self.name_braceletNum_formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.name_braceletNum_formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.name_braceletNum_formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.name_braceletNum_formLayout.setObjectName("name_braceletNum_formLayout")
        self.indexLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indexLabel.sizePolicy().hasHeightForWidth())
        self.indexLabel.setSizePolicy(sizePolicy)
        self.indexLabel.setMinimumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.indexLabel.setFont(font)
        self.indexLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                     "color:#ffffff;")
        self.indexLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.indexLabel.setObjectName("indexLabel")
        self.name_braceletNum_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.indexLabel)
        self.indexNumLineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indexNumLineEdit.sizePolicy().hasHeightForWidth())
        self.indexNumLineEdit.setSizePolicy(sizePolicy)
        self.indexNumLineEdit.setMinimumSize(QtCore.QSize(100, 30))
        self.indexNumLineEdit.setMaximumSize(QtCore.QSize(100, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.indexNumLineEdit.setFont(font)
        self.indexNumLineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.indexNumLineEdit.setStyleSheet("background: #ffffff;\n"
                                               "border:2px rounded #232323;\n"
                                               "border-radius: 10px;\n"
                                               "border-style: outset;\n"
                                               "border-color: rgb(57, 57, 57);\n"
                                            "color:#000000;")
        self.indexNumLineEdit.setFrame(False)
        self.indexNumLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.indexNumLineEdit.setReadOnly(False)
        self.indexNumLineEdit.setClearButtonEnabled(True)
        self.indexNumLineEdit.setObjectName("indexNumLineEdit")
        self.name_braceletNum_formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.indexNumLineEdit)
        self.nameLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameLabel.sizePolicy().hasHeightForWidth())
        self.nameLabel.setSizePolicy(sizePolicy)
        self.nameLabel.setMinimumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                     "color:#ffffff;")
        self.nameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.name_braceletNum_formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameLineEdit.sizePolicy().hasHeightForWidth())
        self.nameLineEdit.setSizePolicy(sizePolicy)
        self.nameLineEdit.setMinimumSize(QtCore.QSize(210, 30))
        self.nameLineEdit.setMaximumSize(QtCore.QSize(210, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.nameLineEdit.setStyleSheet("background: #ffffff;\n"
                                        "border:2px rounded #232323;\n"
                                        "border-radius: 10px;\n"
                                        "border-style: outset;\n"
                                        "border-color: rgb(57, 57, 57);\n"
                                        "padding-left:25px;"
                                        "color:#000000;")
        self.nameLineEdit.setFrame(False)
        self.nameLineEdit.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.nameLineEdit.setReadOnly(False)
        self.nameLineEdit.setClearButtonEnabled(True)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.name_braceletNum_formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.braceletNumLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.braceletNumLabel.sizePolicy().hasHeightForWidth())
        self.braceletNumLabel.setSizePolicy(sizePolicy)
        self.braceletNumLabel.setMinimumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.braceletNumLabel.setFont(font)
        self.braceletNumLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                            "color:#ffffff;")
        self.braceletNumLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.braceletNumLabel.setWordWrap(True)
        self.braceletNumLabel.setObjectName("braceletNumLabel")
        self.name_braceletNum_formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.braceletNumLabel)
        self.braceletNumLineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.braceletNumLineEdit.sizePolicy().hasHeightForWidth())
        self.braceletNumLineEdit.setSizePolicy(sizePolicy)
        self.braceletNumLineEdit.setMinimumSize(QtCore.QSize(100, 30))
        self.braceletNumLineEdit.setMaximumSize(QtCore.QSize(100, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.braceletNumLineEdit.setFont(font)
        self.braceletNumLineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.braceletNumLineEdit.setStyleSheet("background: #ffffff;\n"
                                               "border:2px rounded #232323;\n"
                                               "border-radius: 10px;\n"
                                               "border-style: outset;\n"
                                               "border-color: rgb(57, 57, 57);\n"
                                               "color:#000000;")
        self.braceletNumLineEdit.setFrame(False)
        self.braceletNumLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.braceletNumLineEdit.setReadOnly(False)
        self.braceletNumLineEdit.setClearButtonEnabled(True)
        self.braceletNumLineEdit.setObjectName("braceletNumLineEdit")
        self.name_braceletNum_formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.braceletNumLineEdit)
        self.parentLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parentLabel.sizePolicy().hasHeightForWidth())
        self.parentLabel.setSizePolicy(sizePolicy)
        self.parentLabel.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.parentLabel.setFont(font)
        self.parentLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                       "color:#ffffff;")
        self.parentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.parentLabel.setObjectName("parentLabel")
        self.name_braceletNum_formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.parentLabel)
        self.ParentLineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ParentLineEdit.sizePolicy().hasHeightForWidth())
        self.ParentLineEdit.setSizePolicy(sizePolicy)
        self.ParentLineEdit.setMinimumSize(QtCore.QSize(210, 32))
        self.ParentLineEdit.setMaximumSize(QtCore.QSize(210, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.ParentLineEdit.setFont(font)
        self.ParentLineEdit.setStyleSheet("background: #ffffff;\n"
                                          "border:2px rounded;\n"
                                          "border-radius: 10px;\n"
                                          "border-style: outset;\n"
                                          "border-color: rgb(57, 57, 57);\n"
                                          "color:#000000;")
        self.ParentLineEdit.setFrame(False)
        self.ParentLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ParentLineEdit.setReadOnly(False)
        self.ParentLineEdit.setObjectName("ParentLineEdit")
        self.name_braceletNum_formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ParentLineEdit)
        self.parentIDLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parentIDLabel.sizePolicy().hasHeightForWidth())
        self.parentIDLabel.setSizePolicy(sizePolicy)
        self.parentIDLabel.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.parentIDLabel.setFont(font)
        self.parentIDLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                         "color:#ffffff;")
        self.parentIDLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.parentIDLabel.setObjectName("parentIDLabel")
        self.name_braceletNum_formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.parentIDLabel)
        self.ParentIDLineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ParentIDLineEdit.sizePolicy().hasHeightForWidth())
        self.ParentIDLineEdit.setSizePolicy(sizePolicy)
        self.ParentIDLineEdit.setMinimumSize(QtCore.QSize(130, 30))
        self.ParentIDLineEdit.setMaximumSize(QtCore.QSize(130, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.ParentIDLineEdit.setFont(font)
        self.ParentIDLineEdit.setStyleSheet("background: #ffffff;\n"
                                            "border:2px rounded;\n"
                                            "border-radius: 10px;\n"
                                            "border-style: outset;\n"
                                            "border-color: rgb(57, 57, 57);\n"
                                            "color:#000000;")
        self.ParentIDLineEdit.setFrame(False)
        self.ParentIDLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ParentIDLineEdit.setReadOnly(False)
        self.ParentIDLineEdit.setObjectName("ParentIDLineEdit")
        self.name_braceletNum_formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ParentIDLineEdit)
        self.bodyLayout.addLayout(self.name_braceletNum_formLayout)
        self.time_hours_formLayout = QtWidgets.QFormLayout()
        self.time_hours_formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.time_hours_formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.time_hours_formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.time_hours_formLayout.setObjectName("time_hours_formLayout")
        self.totalTimeLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalTimeLabel.sizePolicy().hasHeightForWidth())
        self.totalTimeLabel.setSizePolicy(sizePolicy)
        self.totalTimeLabel.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.totalTimeLabel.setFont(font)
        self.totalTimeLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                          "color:#ffffff;")
        self.totalTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.totalTimeLabel.setObjectName("totalTimeLabel")
        self.time_hours_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.totalTimeLabel)
        self.putTotalTimeLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.putTotalTimeLabel.sizePolicy().hasHeightForWidth())
        self.putTotalTimeLabel.setSizePolicy(sizePolicy)
        self.putTotalTimeLabel.setMinimumSize(QtCore.QSize(130, 30))
        self.putTotalTimeLabel.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.putTotalTimeLabel.setFont(font)
        self.putTotalTimeLabel.setStyleSheet("QLabel {\n"
                                             "    border: 2px rounded;\n"
                                             "    border-color: rgb(57, 57, 57);\n"
                                             "    border-radius: 8px;\n"
                                             "    border-style: outset;\n"
                                             "    background-color: #ffffff;\n"
                                             "    padding: 5 px;\n"
                                             "    color:#000000;\n"
                                             "}")
        self.putTotalTimeLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.putTotalTimeLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.putTotalTimeLabel.setLineWidth(2)
        self.putTotalTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.putTotalTimeLabel.setObjectName("putTotalTimeLabel")
        self.time_hours_formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.putTotalTimeLabel)
        self.extraTimeLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extraTimeLabel.sizePolicy().hasHeightForWidth())
        self.extraTimeLabel.setSizePolicy(sizePolicy)
        self.extraTimeLabel.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.extraTimeLabel.setFont(font)
        self.extraTimeLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                          "color:#ffffff;")
        self.extraTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.extraTimeLabel.setObjectName("extraTimeLabel")
        self.time_hours_formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.extraTimeLabel)
        self.exitTimeLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitTimeLabel.sizePolicy().hasHeightForWidth())
        self.exitTimeLabel.setSizePolicy(sizePolicy)
        self.exitTimeLabel.setMinimumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.exitTimeLabel.setFont(font)
        self.exitTimeLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                         "color:#ffffff;")
        self.exitTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.exitTimeLabel.setWordWrap(True)
        self.exitTimeLabel.setObjectName("exitTimeLabel")
        self.time_hours_formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.exitTimeLabel)
        self.putExitTimeLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.putExitTimeLabel.sizePolicy().hasHeightForWidth())
        self.putExitTimeLabel.setSizePolicy(sizePolicy)
        self.putExitTimeLabel.setMinimumSize(QtCore.QSize(130, 30))
        self.putExitTimeLabel.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.putExitTimeLabel.setFont(font)
        self.putExitTimeLabel.setStyleSheet("QLabel {\n"
                                            "    border: 2px rounded;\n"
                                            "    border-color: rgb(57, 57, 57);\n"
                                            "    border-radius: 8px;\n"
                                            "    border-style: outset;\n"
                                            "    background-color: #ffffff;\n"
                                            "    padding: 5 px;\n"
                                            "    color:#000000;\n"
                                            "}")
        self.putExitTimeLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.putExitTimeLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.putExitTimeLabel.setLineWidth(2)
        self.putExitTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.putExitTimeLabel.setObjectName("putExitTimeLabel")
        self.time_hours_formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.putExitTimeLabel)
        self.totalTimeComboBox_2 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalTimeComboBox_2.sizePolicy().hasHeightForWidth())
        self.totalTimeComboBox_2.setSizePolicy(sizePolicy)
        self.totalTimeComboBox_2.setMinimumSize(QtCore.QSize(130, 22))
        self.totalTimeComboBox_2.setMaximumSize(QtCore.QSize(210, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.totalTimeComboBox_2.setFont(font)
        self.totalTimeComboBox_2.setMouseTracking(True)
        self.totalTimeComboBox_2.setStyleSheet("QComboBox {\n"
                                               "    border: 2px rounded;\n"
                                               "    border-radius: 8px;\n"
                                               "    border-style: outset;   \n"
                                               "    border-color: rgb(57, 57, 57);\n"
                                               "    padding: 5px 18px 5px 5px;   \n"
                                               "    background-color:#ffffff;\n"
                                               "    color:#000000;\n"
                                               "}\n"
                                               "\n"
                                               "QComboBox QAbstractItemView::item{\n"
                                               "    background-color: #ffffff; \n"
                                               "}\n"
                                               "\n"
                                               "QComboBox QAbstractItemView::item:hover {\n"
                                               "    color: #ffffff;\n"
                                               "}")
        self.totalTimeComboBox_2.setObjectName("totalTimeComboBox_2")
        self.totalTimeComboBox_2.addItem("")
        # self.totalTimeComboBox_2.addItem("")
        # self.totalTimeComboBox_2.addItem("")
        # self.totalTimeComboBox_2.addItem("")
        # self.totalTimeComboBox_2.addItem("")
        self.time_hours_formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.totalTimeComboBox_2)
        self.bodyLayout.addLayout(self.time_hours_formLayout)
        self.price_formLayout = QtWidgets.QFormLayout()
        self.price_formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.price_formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.price_formLayout.setObjectName("price_formLayout")
        self.priceLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.priceLabel.sizePolicy().hasHeightForWidth())
        self.priceLabel.setSizePolicy(sizePolicy)
        self.priceLabel.setMinimumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.priceLabel.setFont(font)
        self.priceLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                      "color:#ffffff;")
        self.priceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.priceLabel.setWordWrap(True)
        self.priceLabel.setObjectName("priceLabel")
        self.price_formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.priceLabel)
        self.putPriceLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.putPriceLabel.sizePolicy().hasHeightForWidth())
        self.putPriceLabel.setSizePolicy(sizePolicy)
        self.putPriceLabel.setMinimumSize(QtCore.QSize(130, 30))
        self.putPriceLabel.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.putPriceLabel.setFont(font)
        self.putPriceLabel.setStyleSheet("QLabel {\n"
                                         "    border: 2px rounded;\n"
                                         "    border-color: rgb(57, 57, 57);\n"
                                         "    border-radius: 8px;\n"
                                         "    border-style: outset;\n"
                                         "    background-color: #ffffff;\n"
                                         "    padding: 5 px;\n"
                                         "    color:#000000;\n"
                                         "}")
        self.putPriceLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.putPriceLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.putPriceLabel.setLineWidth(2)
        self.putPriceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.putPriceLabel.setObjectName("putPriceLabel")
        self.price_formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.putPriceLabel)
        self.payedLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payedLabel.sizePolicy().hasHeightForWidth())
        self.payedLabel.setSizePolicy(sizePolicy)
        self.payedLabel.setMinimumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.payedLabel.setFont(font)
        self.payedLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                      "color:#ffffff;")
        self.payedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.payedLabel.setObjectName("payedLabel")
        self.price_formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.payedLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.YesPayedRadioButton = QtWidgets.QRadioButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.YesPayedRadioButton.sizePolicy().hasHeightForWidth())
        self.YesPayedRadioButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.YesPayedRadioButton.setFont(font)
        self.YesPayedRadioButton.setCheckable(True)
        self.YesPayedRadioButton.setChecked(False)
        self.YesPayedRadioButton.setAutoRepeat(False)
        self.YesPayedRadioButton.setObjectName("YesPayedRadioButton")
        self.YesPayedRadioButton.setStyleSheet("color:#000000;")
        self.YesPayedRadioButton.setAutoExclusive(False)
        self.horizontalLayout_3.addWidget(self.YesPayedRadioButton)
        self.NoPayedRadioButton = QtWidgets.QRadioButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NoPayedRadioButton.sizePolicy().hasHeightForWidth())
        self.NoPayedRadioButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.NoPayedRadioButton.setFont(font)
        self.NoPayedRadioButton.setCheckable(True)
        self.NoPayedRadioButton.setChecked(False)
        self.NoPayedRadioButton.setAutoRepeat(False)
        self.NoPayedRadioButton.setObjectName("NoPayedRadioButton")
        self.NoPayedRadioButton.setStyleSheet("color:#000000;")
        self.NoPayedRadioButton.setAutoExclusive(False)
        self.horizontalLayout_3.addWidget(self.NoPayedRadioButton)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.price_formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.putExtraPriceLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.putExtraPriceLabel.sizePolicy().hasHeightForWidth())
        self.putExtraPriceLabel.setSizePolicy(sizePolicy)
        self.putExtraPriceLabel.setMinimumSize(QtCore.QSize(130, 30))
        self.putExtraPriceLabel.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.putExtraPriceLabel.setFont(font)
        self.putExtraPriceLabel.setStyleSheet("QLabel {\n"
                                              "    border: 2px rounded;\n"
                                              "    border-color: rgb(57, 57, 57);\n"
                                              "    border-radius: 8px;\n"
                                              "    border-style: outset;\n"
                                              "    background-color: #ffffff;\n"
                                              "    padding: 5 px;\n"
                                              "    color:#000000;\n"
                                              "}")
        self.putExtraPriceLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.putExtraPriceLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.putExtraPriceLabel.setLineWidth(2)
        self.putExtraPriceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.putExtraPriceLabel.setObjectName("putExtraPriceLabel")
        self.price_formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.putExtraPriceLabel)
        self.addedValueLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addedValueLabel.sizePolicy().hasHeightForWidth())
        self.addedValueLabel.setSizePolicy(sizePolicy)
        self.addedValueLabel.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.addedValueLabel.setFont(font)
        self.addedValueLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                           "color:#ffffff;")
        self.addedValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.addedValueLabel.setObjectName("addedValueLabel")
        self.price_formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.addedValueLabel)
        self.bodyLayout.addLayout(self.price_formLayout)
        self.verticalLayout_2.addLayout(self.bodyLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.dialogEditRequestsLayout = QtWidgets.QHBoxLayout()
        self.dialogEditRequestsLayout.setSpacing(30)
        self.dialogEditRequestsLayout.setObjectName("dialogEditRequestsLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dialogEditRequestsLayout.addItem(spacerItem1)
        self.acceptEditRequestPushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acceptEditRequestPushButton.sizePolicy().hasHeightForWidth())
        self.acceptEditRequestPushButton.setSizePolicy(sizePolicy)
        self.acceptEditRequestPushButton.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.acceptEditRequestPushButton.setFont(font)
        self.acceptEditRequestPushButton.setStyleSheet("QPushButton{\n"
                                                       "    padding: 0px 10px 0px 10px;\n"
                                                       "    background: rgb(163, 111, 61);\n"
                                                       "    color: #232323;\n"
                                                       "    border:1px rounded #232323;\n"
                                                       "    border-radius: 5px;\n"
                                                       "    border-style: outset;\n"
                                                       "}\n"
                                                       "\n"
                                                       "QPushButton:hover {\n"
                                                       "    background: #e0d1bd;\n"
                                                       "    }\n"
                                                       "\n"
                                                       "QPushButton:pressed {\n"
                                                       "    border-style: inset;\n"
                                                       "    background: rgb(214, 218, 218);\n"
                                                       "    }")
        self.acceptEditRequestPushButton.setObjectName("acceptEditRequestPushButton")
        self.dialogEditRequestsLayout.addWidget(self.acceptEditRequestPushButton)
        self.denyEditRequestPushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.denyEditRequestPushButton.sizePolicy().hasHeightForWidth())
        self.denyEditRequestPushButton.setSizePolicy(sizePolicy)
        self.denyEditRequestPushButton.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.denyEditRequestPushButton.setFont(font)
        self.denyEditRequestPushButton.setStyleSheet("QPushButton{\n"
                                                     "    padding: 0px 10px 0px 10px;\n"
                                                     "    background: rgb(230, 230, 230);\n"
                                                     "    color: #232323;\n"
                                                     "    border:1px rounded #232323;\n"
                                                     "    border-radius: 5px;\n"
                                                     "    border-style: outset;\n"
                                                     "}\n"
                                                     "\n"
                                                     "QPushButton:hover {\n"
                                                     "    background: rgb(255,255,255);\n"
                                                     "    }\n"
                                                     "\n"
                                                     "QPushButton:pressed {\n"
                                                     "    border-style: inset;\n"
                                                     "    background: rgb(214, 218, 218);\n"
                                                     "    }")
        self.denyEditRequestPushButton.setObjectName("denyEditRequestPushButton")
        self.dialogEditRequestsLayout.addWidget(self.denyEditRequestPushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dialogEditRequestsLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.dialogEditRequestsLayout)

        self.retranslateUi(Form)
        self.totalTimeComboBox_2.setCurrentIndex(0)
        self.YesPayedRadioButton.toggled['bool'].connect(self.NoPayedRadioButton.setDisabled)  # type: ignore
        self.NoPayedRadioButton.toggled['bool'].connect(self.YesPayedRadioButton.setDisabled)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

        # connecting acceptEditRequest and denyEditRequest buttons

        self.acceptEditRequestPushButton.clicked.connect(self.manageUsersEdition)
        self.denyEditRequestPushButton.clicked.connect(self.closeEdit)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "EDITAR USUARIOS"))
        self.editLabel.setText(_translate("Form", "EDITAR USUARIO"))
        self.indexLabel.setText(_translate("Form", "Index"))
        self.indexNumLineEdit.setPlaceholderText(_translate("Form", "1, 2, 3, ..."))
        self.indexNumLineEdit.setToolTip(_translate("Form", "Indice"))
        self.nameLabel.setText(_translate("Form", "Nombre"))
        self.nameLineEdit.setToolTip(_translate("Form", "Total de personas"))
        self.nameLineEdit.setPlaceholderText(_translate("Form", "Ej: Miguel Lopez"))
        self.braceletNumLabel.setText(_translate("Form", "Número de manilla"))
        self.braceletNumLineEdit.setToolTip(_translate("Form", "Total de personas"))
        self.braceletNumLineEdit.setPlaceholderText(_translate("Form", "0"))
        self.parentLabel.setText(_translate("Form", "Acudiente"))
        self.ParentLineEdit.setToolTip(_translate("Form", "Total de personas"))
        self.ParentLineEdit.setPlaceholderText(_translate("Form", "Ej: Juliana Vélez"))
        self.parentIDLabel.setText(_translate("Form", "Acudiente-ID"))
        self.ParentIDLineEdit.setToolTip(_translate("Form", "Total de personas"))
        self.ParentIDLineEdit.setPlaceholderText(_translate("Form", "Ej: La cedula"))
        self.totalTimeLabel.setText(_translate("Form", "Tiempo"))
        self.putTotalTimeLabel.setText(_translate("Form", "00:00"))
        self.extraTimeLabel.setText(_translate("Form", "Tiempo extra"))
        self.exitTimeLabel.setText(_translate("Form", "Hora estimada de salida"))
        self.putExitTimeLabel.setText(_translate("Form", "00:00"))
        self.totalTimeComboBox_2.setCurrentText(_translate("Form", "Seleccione"))
        self.totalTimeComboBox_2.setItemText(0, _translate("Form", "Seleccione"))
        self.priceLabel.setText(_translate("Form", "Valor total a pagar"))
        self.putPriceLabel.setText(_translate("Form", "$0"))
        self.payedLabel.setText(_translate("Form", "Cancelado"))
        self.YesPayedRadioButton.setText(_translate("Form", "SI"))
        self.NoPayedRadioButton.setText(_translate("Form", "NO"))
        self.putExtraPriceLabel.setText(_translate("Form", "$0"))
        self.addedValueLabel.setText(_translate("Form", "Valor añadido"))
        self.acceptEditRequestPushButton.setText(_translate("Form", "Aceptar"))
        self.denyEditRequestPushButton.setText(_translate("Form", "Cancelar"))

    @staticmethod
    def showPopUp(show_text, message_type):
        message = QMessageBox()
        # message.windowIcon()
        message.setWindowTitle("Arenero PlayKids")
        message.setText(show_text)
        message.setIcon(message_type)
        message.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        retval = message.exec_()

    def showEdit(self, retrievedData):
        self.editWidgetInstance = QtWidgets.QWidget()
        # self.registerWidgetInstance.setWindowIcon(QtGui.QIcon(":/images/fact.png"))
        self.setupUi(self.editWidgetInstance)
        UiForm.formInstance = self.editWidgetInstance
        self.loadUserToEdit(retrievedData)
        self.editWidgetInstance.show()

    @staticmethod
    def closeEdit():
        return UiForm.formInstance.close() if UiForm.formInstance is not None else 0

    def loadUserToEdit(self, retrievedData):
        UiForm.userToEdit = retrievedData
        print("Usuario a editar -> ", UiForm.userToEdit, " CARGADO correctamente")
        if UiForm.userToEdit[0] is not None:
            font = QtGui.QFont()
            font.setPointSize(1)
            self.indexNumLineEdit.setText(str(retrievedData[1]))
            self.nameLineEdit.setText(retrievedData[0][0])
            self.braceletNumLineEdit.setText(retrievedData[0][1])
            self.ParentLineEdit.setText(retrievedData[0][8])
            self.ParentIDLineEdit.setText(retrievedData[0][9])
            self.putTotalTimeLabel.setText(retrievedData[0][2])
            self.putExitTimeLabel.setText(retrievedData[0][4])
            if retrievedData[0][7] == 'False':
                self.NoPayedRadioButton.setChecked(True)
            elif retrievedData[0][7] == 'True':
                self.YesPayedRadioButton.setChecked(True)



    def validateEditedFields(self, user):
        fieldsWithErrors = []
        excludedFields = ["Dinero", "Pagado", "Tiempo"]  # TODO: need to fix timeComboBox verification and data visualization of the current time selected
        noTAdmitedValues = ["", None]
        for field, value in user.items():
            if field not in excludedFields:
                if value in noTAdmitedValues:
                    fieldsWithErrors.append(field)
        if len(fieldsWithErrors) != 0:
            separator = ","
            self.showPopUp(f"Valores no permitidos en los campos {separator.join(fieldsWithErrors)}",
                             QMessageBox.Warning)
            return False
        else:
            return True

    def manageUsersEdition(self):
        # TODO: Do we need to hava e field that edit if the user is Vip?
        userChanges = {"Index": self.indexNumLineEdit.text().strip(),
                       "Nombre": self.nameLineEdit.text().strip(),
                       "Manilla": self.braceletNumLineEdit.text().strip(),
                       "Tiempo": self.totalTimeComboBox_2.currentText(),
                       "Acudiente": self.ParentLineEdit.text().strip(),
                       "ID-Acudiente": self.ParentIDLineEdit.text().strip(),
                       "Dinero": calcChargingPrice(self.totalTimeComboBox_2.currentText(), "default"), #left this if self.YesVipUserRadioButton.isChecked() else calcChargingPrice(self.totalTimeComboBox.currentText(), "default")
                       "Pagado": True if self.YesPayedRadioButton.isChecked() else False,
                       "Hora salida": self.putExitTimeLabel, "Sale": False}
        if self.validateEditedFields(userChanges):
            print("USUARIO EDITADO CON EXITO! -> ")
            CrudLocalStorage.setChange(True)
            # editUser(userChanges)
            self.closeEdit()
