# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/miguellopez/Desktop/PROYECTS/PAGOS/ARENERO-RAMIRO/FRONTEND/views/QT_DESIGNS/designs/evacuate.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from FRONTEND import evacuateConfirmationDialog, evacuateConfirmationForced, evacuateConfirmationDeny
from FRONTEND.constantsAndOthers import placeholders

class UiForm(object):
    formInstance = None
    userToEvacuate = None

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(656, 311)
        Form.setMinimumSize(QtCore.QSize(656, 311))
        Form.setMaximumSize(QtCore.QSize(656, 311))
        Form.setStyleSheet("background-color:#ffc3ae;color:#000000")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setSpacing(26)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(18)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setScaledContents(False)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setWordWrap(True)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_2.setStyleSheet("color:#000000;")
        self.horizontalLayout.addWidget(self.label_2)
        self.searchLineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchLineEdit.sizePolicy().hasHeightForWidth())
        self.searchLineEdit.setSizePolicy(sizePolicy)
        self.searchLineEdit.setMinimumSize(QtCore.QSize(230, 32))
        self.searchLineEdit.setMaximumSize(QtCore.QSize(230, 32))
        self.searchLineEdit.setMouseTracking(True)
        self.searchLineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.searchLineEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.searchLineEdit.setStyleSheet("QLineEdit{\n"
                                          "    background-color: #ffffff;\n"
                                          "    border: 1px rounded #232323;\n"
                                          "    border-radius: 12px;\n"
                                          "    border-style: outset;\n"
                                          "    font-family: \"Helvetica\";\n"
                                          "    font-weight: 400;\n"
                                          "    font-size: 18px;\n"
                                          "    text-align: left;\n"
                                          "padding-left: 10px;\n"
                                          "color:#000000;}\n"
                                          "\n"
                                          "")
        self.searchLineEdit.setText("")
        self.searchLineEdit.setFrame(False)
        self.searchLineEdit.setReadOnly(False)
        self.searchLineEdit.setClearButtonEnabled(True)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.horizontalLayout.addWidget(self.searchLineEdit)
        self.searchRecordPushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchRecordPushButton.sizePolicy().hasHeightForWidth())
        self.searchRecordPushButton.setSizePolicy(sizePolicy)
        self.searchRecordPushButton.setMinimumSize(QtCore.QSize(50, 32))
        self.searchRecordPushButton.setMaximumSize(QtCore.QSize(50, 32))
        self.searchRecordPushButton.setStyleSheet("QPushButton{\n"
                                                  "    padding: 0px 10px 0px 10px;\n"
                                                  "    background: rgb(255, 246, 53);\n"
                                                  "    color: #ffffff;\n"
                                                  "    border:1px rounded #232323;\n"
                                                  "    border-radius: 10px;\n"
                                                  "    border-style: outset;\n"
                                                  "}\n"
                                                  "\n"
                                                  "QPushButton:hover {\n"
                                                  "    background: rgb(232, 218, 70);\n"
                                                  "    }\n"
                                                  "\n"
                                                  "QPushButton:pressed {\n"
                                                  "    border-style: inset;\n"
                                                  "    background: rgb(214, 218, 218);\n"
                                                  "    }")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/usedIcons/icons8-search-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchRecordPushButton.setIcon(icon)
        self.searchRecordPushButton.setIconSize(QtCore.QSize(24, 24))
        self.searchRecordPushButton.setObjectName("searchRecordPushButton")
        self.horizontalLayout.addWidget(self.searchRecordPushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 20, -1, 12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameLabel.sizePolicy().hasHeightForWidth())
        self.nameLabel.setSizePolicy(sizePolicy)
        self.nameLabel.setMinimumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                     "color:#ffffff;")
        self.nameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.putNameLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.putNameLabel.sizePolicy().hasHeightForWidth())
        self.putNameLabel.setSizePolicy(sizePolicy)
        self.putNameLabel.setMinimumSize(QtCore.QSize(210, 35))
        self.putNameLabel.setMaximumSize(QtCore.QSize(210, 35))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.putNameLabel.setFont(font)
        self.putNameLabel.setStyleSheet("QLabel {\n"
                                        "    border: 2px rounded;\n"
                                        "    border-color: rgb(57, 57, 57);\n"
                                        "    border-radius: 8px;\n"
                                        "    border-style: outset;\n"
                                        "    background-color: #ffffff;\n"
                                        "    padding: 5 px;\n"
                                        "color:#000000;}")
        self.putNameLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.putNameLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.putNameLabel.setLineWidth(2)
        self.putNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.putNameLabel.setObjectName("putNameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.putNameLabel)
        self.horizontalLayout_3.addLayout(self.formLayout)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName("formLayout_3")
        self.saleLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saleLabel.sizePolicy().hasHeightForWidth())
        self.saleLabel.setSizePolicy(sizePolicy)
        self.saleLabel.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.saleLabel.setFont(font)
        self.saleLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                     "color:#ffffff;")
        self.saleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.saleLabel.setWordWrap(True)
        self.saleLabel.setObjectName("saleLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.saleLabel)
        self.putSaleLabel_3 = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.putSaleLabel_3.sizePolicy().hasHeightForWidth())
        self.putSaleLabel_3.setSizePolicy(sizePolicy)
        self.putSaleLabel_3.setMinimumSize(QtCore.QSize(50, 30))
        self.putSaleLabel_3.setMaximumSize(QtCore.QSize(50, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.putSaleLabel_3.setFont(font)
        self.putSaleLabel_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.putSaleLabel_3.setAutoFillBackground(False)
        self.putSaleLabel_3.setStyleSheet("background: rgb(97, 177, 66);\n"
                                          "border:1px rounded #232323;\n"
                                          "border-radius: 10px;\n"
                                          "border-style: outset;")
        self.putSaleLabel_3.setMaxLength(0)
        self.putSaleLabel_3.setFrame(False)
        self.putSaleLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.putSaleLabel_3.setReadOnly(True)
        self.putSaleLabel_3.setPlaceholderText("")
        self.putSaleLabel_3.setObjectName("putSaleLabel_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.putSaleLabel_3)
        self.payedLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payedLabel.sizePolicy().hasHeightForWidth())
        self.payedLabel.setSizePolicy(sizePolicy)
        self.payedLabel.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.payedLabel.setFont(font)
        self.payedLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                      "color:#ffffff;")
        self.payedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.payedLabel.setWordWrap(True)
        self.payedLabel.setObjectName("payedLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.payedLabel)
        self.putPayedLabel = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.putPayedLabel.sizePolicy().hasHeightForWidth())
        self.putPayedLabel.setSizePolicy(sizePolicy)
        self.putPayedLabel.setMinimumSize(QtCore.QSize(50, 30))
        self.putPayedLabel.setMaximumSize(QtCore.QSize(50, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.putPayedLabel.setFont(font)
        self.putPayedLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.putPayedLabel.setAutoFillBackground(False)
        self.putPayedLabel.setStyleSheet("background: rgb(229, 0, 5);\n"
                                         "border:1px rounded #232323;\n"
                                         "border-radius: 10px;\n"
                                         "border-style: outset;")
        self.putPayedLabel.setMaxLength(0)
        self.putPayedLabel.setFrame(False)
        self.putPayedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.putPayedLabel.setReadOnly(True)
        self.putPayedLabel.setPlaceholderText("")
        self.putPayedLabel.setObjectName("putPayedLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.putPayedLabel)
        self.horizontalLayout_3.addLayout(self.formLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(208, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.evacuatePushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evacuatePushButton.sizePolicy().hasHeightForWidth())
        self.evacuatePushButton.setSizePolicy(sizePolicy)
        self.evacuatePushButton.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.evacuatePushButton.setFont(font)
        self.evacuatePushButton.setStyleSheet("QPushButton{\n"
                                              "    padding: 0px 10px 0px 10px;\n"
                                              "    background: #e0d1bd;\n"
                                              "    color: #232323;\n"
                                              "    border:1px rounded #232323;\n"
                                              "    border-radius: 5px;\n"
                                              "    border-style: outset;\n"
                                              "}\n"
                                              "\n"
                                              "QPushButton:hover {\n"
                                              "    background: rgb(163, 111, 61);\n"
                                              "    }\n"
                                              "\n"
                                              "QPushButton:pressed {\n"
                                              "    border-style: inset;\n"
                                              "    background: rgb(214, 218, 218);\n"
                                              "    }")
        self.evacuatePushButton.setObjectName("evacuatePushButton")
        self.horizontalLayout_2.addWidget(self.evacuatePushButton)
        self.cancelEvacuationPushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelEvacuationPushButton.sizePolicy().hasHeightForWidth())
        self.cancelEvacuationPushButton.setSizePolicy(sizePolicy)
        self.cancelEvacuationPushButton.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cancelEvacuationPushButton.setFont(font)
        self.cancelEvacuationPushButton.setStyleSheet("QPushButton{\n"
                                                      "    padding: 0px 10px 0px 10px;\n"
                                                      "    background: rgb(230, 230, 230);\n"
                                                      "    color: #232323;\n"
                                                      "    border:1px rounded #232323;\n"
                                                      "    border-radius: 5px;\n"
                                                      "    border-style: outset;\n"
                                                      "}\n"
                                                      "\n"
                                                      "QPushButton:hover {\n"
                                                      "    background: rgb(255,255,255);\n"
                                                      "    }\n"
                                                      "\n"
                                                      "QPushButton:pressed {\n"
                                                      "    border-style: inset;\n"
                                                      "    background: rgb(214, 218, 218);\n"
                                                      "    }")
        self.cancelEvacuationPushButton.setObjectName("cancelEvacuationPushButton")
        self.horizontalLayout_2.addWidget(self.cancelEvacuationPushButton)
        self.forceEvacuationPushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forceEvacuationPushButton.sizePolicy().hasHeightForWidth())
        self.forceEvacuationPushButton.setSizePolicy(sizePolicy)
        self.forceEvacuationPushButton.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.forceEvacuationPushButton.setFont(font)
        self.forceEvacuationPushButton.setStyleSheet("QPushButton{\n"
                                                     "    padding: 0px 10px 0px 10px;\n"
                                                     "    background: rgb(83, 152, 47);\n"
                                                     "    color: #232323;\n"
                                                     "    border:1px rounded #232323;\n"
                                                     "    border-radius: 5px;\n"
                                                     "    border-style: outset;\n"
                                                     "}\n"
                                                     "\n"
                                                     "QPushButton:hover {\n"
                                                     "    background: rgb(103, 191, 58);\n"
                                                     "    }\n"
                                                     "\n"
                                                     "QPushButton:pressed {\n"
                                                     "    border-style: inset;\n"
                                                     "    background: rgb(214, 218, 218);\n"
                                                     "    }")
        self.forceEvacuationPushButton.setObjectName("forceEvacuationPushButton")
        self.horizontalLayout_2.addWidget(self.forceEvacuationPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)

        # Connecting accept, cancel and forced evacuation
        self.evacuatePushButton.clicked.connect(self.validateFieldsWithoutForce)
        self.cancelEvacuationPushButton.clicked.connect(self.closeEvacuation)
        self.forceEvacuationPushButton.clicked.connect(self.validateFieldsWithForce)

        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "EVACUAR USUARIO"))
        self.titleLabel.setText(_translate("Form", "EVACUAR USUARIO"))
        self.label_2.setText(_translate("Form", "IDENTIFICADOR"))
        self.searchLineEdit.setPlaceholderText(_translate("Form", placeholders['PH_SEARCH_RECORD']))
        self.nameLabel.setText(_translate("Form", "Nombre"))
        self.putNameLabel.setText(_translate("Form", placeholders['PH_NAME']))
        self.saleLabel.setText(_translate("Form", "Sale"))
        self.putSaleLabel_3.setToolTip(_translate("Form", "Total de personas"))
        self.payedLabel.setText(_translate("Form", "Cancelado"))
        self.putPayedLabel.setToolTip(_translate("Form", "Total de personas"))
        self.evacuatePushButton.setText(_translate("Form", "Evacuar"))
        self.cancelEvacuationPushButton.setText(_translate("Form", "Cancelar"))
        self.forceEvacuationPushButton.setText(_translate("Form", "Forzar evacuación"))

    def showEvacuate(self, retrievedData):
        self.evacuateWidgetInstance = QtWidgets.QWidget()
        # self.registerWidgetInstance.setWindowIcon(QtGui.QIcon(":/images/fact.png"))
        self.setupUi(self.evacuateWidgetInstance)
        UiForm.formInstance = self.evacuateWidgetInstance
        self.loadUserToEvacuate(retrievedData)
        self.evacuateWidgetInstance.show()

    def launchEvacuateConfirmationDeny(self):
        self.viewEvacuateConfirmationDeny = evacuateConfirmationDeny.UiForm()
        self.viewEvacuateConfirmationDeny.showEvacuateConfirmationDenied()

    def manageSaleAndPayedLabelVerificationStyle(self, userSaleLabelValue, userPayedLabelValue):
        greenStyle = "background: rgb(97, 177, 66);\nborder:1px rounded #232323;\nborder-radius: 10px;\nborder-style: outset;"
        redStyle = "background: rgb(229, 0, 5);\nborder:1px rounded #232323;\nborder-radius: 10px;\nborder-style: outset;"
        self.putSaleLabel_3.setStyleSheet(greenStyle if userSaleLabelValue == 'True' else redStyle)
        self.putPayedLabel.setStyleSheet(greenStyle if userPayedLabelValue == 'True' else redStyle)

    def loadUserToEvacuate(self, retrievedData):
        UiForm.userToEvacuate = retrievedData
        print("Usuario a eliminar -> ", UiForm.userToEvacuate, " CARGADO correctamente")
        if UiForm.userToEvacuate[0] is not None:
            font = QtGui.QFont()
            font.setPointSize(1)
            self.putNameLabel.setText(retrievedData[0][0])
            self.putSaleLabel_3.setText(retrievedData[0][5])
            self.putSaleLabel_3.setFont(font)
            self.putPayedLabel.setText(retrievedData[0][7])
            self.putPayedLabel.setFont(font)
            self.manageSaleAndPayedLabelVerificationStyle(userSaleLabelValue=retrievedData[0][5], userPayedLabelValue=retrievedData[0][7] )

    @staticmethod
    def closeEvacuation():
        return UiForm.formInstance.close() if UiForm.formInstance is not None else 0

    def validateFieldsWithoutForce(self):
        hasUsersTimeEnd = " "
        hasUserPaid = " "
        if UiForm.userToEvacuate[0] is not None:
            hasUsersTimeEnd = UiForm.userToEvacuate[0][5]
            hasUserPaid = UiForm.userToEvacuate[0][7]

        if hasUsersTimeEnd == "True" and hasUserPaid == "True":
            self.launchEvacuateConfirmation(ableToDelete=True, userToEvacuateIndex=UiForm.userToEvacuate[1])
        else:
            self.launchEvacuateConfirmation(ableToDelete=False, userToEvacuateIndex=UiForm.userToEvacuate[1])

    def validateFieldsWithForce(self):
        if UiForm.userToEvacuate[0] is not None:
            self.launchForcedEvacuate(UiForm.userToEvacuate[1])
        else:
            self.launchEvacuateConfirmationDeny()
    def launchEvacuateConfirmation(self, ableToDelete, userToEvacuateIndex):
        self.viewEvacuateConfirmation = evacuateConfirmationDialog.UiForm()
        self.viewEvacuateConfirmation.showEvacuateConfirmation(ableToDelete, userToEvacuateIndex)

    def launchForcedEvacuate(self, userToEvacuateIndex):
        self.viewForcedEvacuate = evacuateConfirmationForced.UiForm()
        self.viewForcedEvacuate.showForcedEvacuate(userToEvacuateIndex)