# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file
# '../FRONTEND/QT-DESIGNS/designs/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from FRONTEND.views.main import *
from BACKEND.TESTS.unit import generateRandomUsers
from BACKEND.CRUD.CRUD_users import startCountingThread

if __name__ == '__main__':
    # generating random numbers
    generateRandomUsers()
    # starting counting Thread
    startCountingThread()  # TODO: Need to verify if the subproccess does finish when the main thread does it
    print("------------------------PROCESO DE CONTEO INICIADO------------------------")
    app = QtWidgets.QApplication(sys.argv)
    # app.setWindowIcon(QtGui.QIcon(":/images/fact.png"))
    window = QtWidgets.QMainWindow()
    # window.setWindowIcon(QtGui.QIcon(":/images/fact.png"))
    ui = UiMainWindow()  # inicio la aplicacion
    ui.setupUi(window)
    # hide_button_maximize(window)
    window.show()
    sys.exit(app.exec_())

# TODO: Add keyboard shortcuts like command+Q to exit the app,
#  enter to make a search, evacuate or submit inofrmation in general
