# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/miguellopez/Desktop/PROYECTS/PAGOS/ARENERO-RAMIRO/FRONTEND/views/QT_DESIGNS/designs/evacuateConfirmationDeny.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiForm(object):
    formInstance = None

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(413, 117)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(413, 117))
        Form.setMaximumSize(QtCore.QSize(413, 117))
        Form.setStyleSheet("background-color: rgb(169, 201, 202);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.messageLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.messageLabel.setFont(font)
        self.messageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.messageLabel.setWordWrap(True)
        self.messageLabel.setObjectName("messageLabel")
        self.messageLabel.setStyleSheet("color:#000000;")
        self.verticalLayout.addWidget(self.messageLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.acceptConfirmEvacuatePushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acceptConfirmEvacuatePushButton.sizePolicy().hasHeightForWidth())
        self.acceptConfirmEvacuatePushButton.setSizePolicy(sizePolicy)
        self.acceptConfirmEvacuatePushButton.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.acceptConfirmEvacuatePushButton.setFont(font)
        self.acceptConfirmEvacuatePushButton.setStyleSheet("QPushButton{\n"
                                                           "    padding: 0px 10px 0px 10px;\n"
                                                           "    background: #e0d1bd;\n"
                                                           "    color: #232323;\n"
                                                           "    border:1px rounded #232323;\n"
                                                           "    border-radius: 5px;\n"
                                                           "    border-style: outset;\n"
                                                           "}\n"
                                                           "\n"
                                                           "QPushButton:hover {\n"
                                                           "    background: rgb(163, 111, 61);\n"
                                                           "    }\n"
                                                           "\n"
                                                           "QPushButton:pressed {\n"
                                                           "    border-style: inset;\n"
                                                           "    background: rgb(214, 218, 218);\n"
                                                           "    }")
        self.acceptConfirmEvacuatePushButton.setObjectName("acceptConfirmEvacuatePushButton")
        self.horizontalLayout.addWidget(self.acceptConfirmEvacuatePushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)

        # Connecting Accept message button
        self.acceptConfirmEvacuatePushButton.clicked.connect(self.closeEvacuateConfirmationDenied)

        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "CONFIRMACIÓN DE EVACUACIÓN DENEGADA"))
        self.messageLabel.setText(_translate("Form",
                                             "No se puede evacuar al usuario. Este NO HA PAGADO la TARIFA del servicio y/o tiene TIEMPO DISPONIBLE"))
        self.acceptConfirmEvacuatePushButton.setText(_translate("Form", "Aceptar"))

    def showEvacuateConfirmationDenied(self):
        self.evacuateConfirmationDeniedWidgetInstance = QtWidgets.QWidget()
        # self.registerWidgetInstance.setWindowIcon(QtGui.QIcon(":/images/fact.png"))
        self.setupUi(self.evacuateConfirmationDeniedWidgetInstance)
        UiForm.formInstance = self.evacuateConfirmationDeniedWidgetInstance
        self.evacuateConfirmationDeniedWidgetInstance.show()

    @staticmethod
    def closeEvacuateConfirmationDenied():
        return UiForm.formInstance.close() if UiForm.formInstance is not None else 0
