# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file
# '../FRONTEND/views/QT_DESIGNS/designs/search.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from FRONTEND.constantsAndOthers import placeholders


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1170, 426)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1170, 426))
        Form.setMaximumSize(QtCore.QSize(1170, 426))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/usedIcons/icons8-gear-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: rgb(145, 228, 251);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setStyleSheet("color:#000000;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.searchRecordLayout = QtWidgets.QHBoxLayout()
        self.searchRecordLayout.setObjectName("searchRecordLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.searchRecordLayout.addItem(spacerItem)
        self.searchIdentifierLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.searchIdentifierLabel.setFont(font)
        self.searchIdentifierLabel.setObjectName("searchIdentifierLabel")
        self.searchIdentifierLabel.setStyleSheet("color:#000000;")
        self.searchRecordLayout.addWidget(self.searchIdentifierLabel)
        self.searchLineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchLineEdit.sizePolicy().hasHeightForWidth())
        self.searchLineEdit.setSizePolicy(sizePolicy)
        self.searchLineEdit.setMinimumSize(QtCore.QSize(466, 32))
        self.searchLineEdit.setMaximumSize(QtCore.QSize(466, 32))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.searchLineEdit.setFont(font)
        self.searchLineEdit.setMouseTracking(True)
        self.searchLineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.searchLineEdit.setStyleSheet("QLineEdit{\n"
                                          "    background-color: #ffffff;\n"
                                          "    border: 1px rounded #232323;\n"
                                          "    border-radius: 12px;\n"
                                          "    border-style: outset;\n"
                                          "    font-family: \"Helvetica\";\n"
                                          "    font-weight: 400;\n"
                                          "    font-size: 18px;\n"
                                          "    text-align: left;\n"
                                          "    padding-left: 10px;\n"
                                          "    color:#000000;}\n"
                                          "\n"
                                          "")
        self.searchLineEdit.setText("")
        self.searchLineEdit.setFrame(False)
        self.searchLineEdit.setReadOnly(False)
        self.searchLineEdit.setClearButtonEnabled(True)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.searchRecordLayout.addWidget(self.searchLineEdit)
        self.searchRecordPushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchRecordPushButton.sizePolicy().hasHeightForWidth())
        self.searchRecordPushButton.setSizePolicy(sizePolicy)
        self.searchRecordPushButton.setMinimumSize(QtCore.QSize(50, 32))
        self.searchRecordPushButton.setMaximumSize(QtCore.QSize(50, 32))
        self.searchRecordPushButton.setStyleSheet("QPushButton{\n"
                                                  "    padding: 0px 10px 0px 10px;\n"
                                                  "    background: rgb(255, 246, 53);\n"
                                                  "    color: #ffffff;\n"
                                                  "    border:1px rounded #232323;\n"
                                                  "    border-radius: 10px;\n"
                                                  "    border-style: outset;\n"
                                                  "}\n"
                                                  "\n"
                                                  "QPushButton:hover {\n"
                                                  "    background: rgb(232, 218, 70);\n"
                                                  "    }\n"
                                                  "\n"
                                                  "QPushButton:pressed {\n"
                                                  "    border-style: inset;\n"
                                                  "    background: rgb(214, 218, 218);\n"
                                                  "    }")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/usedIcons/icons8-search-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchRecordPushButton.setIcon(icon1)
        self.searchRecordPushButton.setIconSize(QtCore.QSize(24, 24))
        self.searchRecordPushButton.setObjectName("searchRecordPushButton")
        self.searchRecordLayout.addWidget(self.searchRecordPushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.searchRecordLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.searchRecordLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameLabel.sizePolicy().hasHeightForWidth())
        self.nameLabel.setSizePolicy(sizePolicy)
        self.nameLabel.setMinimumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                     "color:#ffffff;")
        self.nameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.braceletNumLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.braceletNumLabel.sizePolicy().hasHeightForWidth())
        self.braceletNumLabel.setSizePolicy(sizePolicy)
        self.braceletNumLabel.setMinimumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.braceletNumLabel.setFont(font)
        self.braceletNumLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                            "color:#ffffff;")
        self.braceletNumLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.braceletNumLabel.setWordWrap(True)
        self.braceletNumLabel.setObjectName("braceletNumLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.braceletNumLabel)
        spacerItem3 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.putNameLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.putNameLabel.sizePolicy().hasHeightForWidth())
        self.putNameLabel.setSizePolicy(sizePolicy)
        self.putNameLabel.setMinimumSize(QtCore.QSize(210, 32))
        self.putNameLabel.setMaximumSize(QtCore.QSize(210, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.putNameLabel.setFont(font)
        self.putNameLabel.setStyleSheet("QLabel {\n"
                                        "    border: 2px rounded;\n"
                                        "    border-color: rgb(57, 57, 57);\n"
                                        "    border-radius: 8px;\n"
                                        "    border-style: outset;\n"
                                        "    background-color: #ffffff;\n"
                                        "    padding: 3px;\n"
                                        "    color:#000000;}")
        self.putNameLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.putNameLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.putNameLabel.setLineWidth(2)
        self.putNameLabel.setTextFormat(QtCore.Qt.AutoText)
        self.putNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.putNameLabel.setObjectName("putNameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.putNameLabel)
        self.putBraceletNumLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.putBraceletNumLabel.sizePolicy().hasHeightForWidth())
        self.putBraceletNumLabel.setSizePolicy(sizePolicy)
        self.putBraceletNumLabel.setMinimumSize(QtCore.QSize(100, 32))
        self.putBraceletNumLabel.setMaximumSize(QtCore.QSize(100, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.putBraceletNumLabel.setFont(font)
        self.putBraceletNumLabel.setStyleSheet("QLabel {\n"
                                               "    border: 2px rounded;\n"
                                               "    border-color: rgb(57, 57, 57);\n"
                                               "    border-radius: 8px;\n"
                                               "    border-style: outset;\n"
                                               "    background-color: #ffffff;\n"
                                               "    padding: 3px;\n"
                                               "    color:#000000;}")
        self.putBraceletNumLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.putBraceletNumLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.putBraceletNumLabel.setLineWidth(2)
        self.putBraceletNumLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.putBraceletNumLabel.setObjectName("putBraceletNumLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.putBraceletNumLabel)
        self.horizontalLayout.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.totalTimeLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalTimeLabel.sizePolicy().hasHeightForWidth())
        self.totalTimeLabel.setSizePolicy(sizePolicy)
        self.totalTimeLabel.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.totalTimeLabel.setFont(font)
        self.totalTimeLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                          "color:#ffffff;")
        self.totalTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.totalTimeLabel.setObjectName("totalTimeLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.totalTimeLabel)
        self.addedTimeLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addedTimeLabel.sizePolicy().hasHeightForWidth())
        self.addedTimeLabel.setSizePolicy(sizePolicy)
        self.addedTimeLabel.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.addedTimeLabel.setFont(font)
        self.addedTimeLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                          "color:#ffffff;")
        self.addedTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.addedTimeLabel.setObjectName("addedTimeLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.addedTimeLabel)
        self.entryHourLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entryHourLabel.sizePolicy().hasHeightForWidth())
        self.entryHourLabel.setSizePolicy(sizePolicy)
        self.entryHourLabel.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.entryHourLabel.setFont(font)
        self.entryHourLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                          "color:#ffffff;")
        self.entryHourLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.entryHourLabel.setObjectName("entryHourLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.entryHourLabel)
        self.exitTimeLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitTimeLabel.sizePolicy().hasHeightForWidth())
        self.exitTimeLabel.setSizePolicy(sizePolicy)
        self.exitTimeLabel.setMinimumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.exitTimeLabel.setFont(font)
        self.exitTimeLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                         "color:#ffffff;")
        self.exitTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.exitTimeLabel.setWordWrap(True)
        self.exitTimeLabel.setObjectName("exitTimeLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.exitTimeLabel)
        self.putTotalTimeLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.putTotalTimeLabel.sizePolicy().hasHeightForWidth())
        self.putTotalTimeLabel.setSizePolicy(sizePolicy)
        self.putTotalTimeLabel.setMinimumSize(QtCore.QSize(130, 30))
        self.putTotalTimeLabel.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.putTotalTimeLabel.setFont(font)
        self.putTotalTimeLabel.setStyleSheet("QLabel {\n"
                                             "    border: 2px rounded;\n"
                                             "    border-color: rgb(57, 57, 57);\n"
                                             "    border-radius: 8px;\n"
                                             "    border-style: outset;\n"
                                             "    background-color: #ffffff;\n"
                                             "    padding: 3px;\n"
                                             "    color:#000000;}")
        self.putTotalTimeLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.putTotalTimeLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.putTotalTimeLabel.setLineWidth(2)
        self.putTotalTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.putTotalTimeLabel.setObjectName("putTotalTimeLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.putTotalTimeLabel)
        self.putAddedTimeLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.putAddedTimeLabel.sizePolicy().hasHeightForWidth())
        self.putAddedTimeLabel.setSizePolicy(sizePolicy)
        self.putAddedTimeLabel.setMinimumSize(QtCore.QSize(130, 30))
        self.putAddedTimeLabel.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.putAddedTimeLabel.setFont(font)
        self.putAddedTimeLabel.setStyleSheet("QLabel {\n"
                                             "    border: 2px rounded;\n"
                                             "    border-color: rgb(57, 57, 57);\n"
                                             "    border-radius: 8px;\n"
                                             "    border-style: outset;\n"
                                             "    background-color: #ffffff;\n"
                                             "    padding: 3px;\n"
                                             "    color:#000000;}")
        self.putAddedTimeLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.putAddedTimeLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.putAddedTimeLabel.setLineWidth(2)
        self.putAddedTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.putAddedTimeLabel.setObjectName("putAddedTimeLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.putAddedTimeLabel)
        self.putEntryHourLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.putEntryHourLabel.sizePolicy().hasHeightForWidth())
        self.putEntryHourLabel.setSizePolicy(sizePolicy)
        self.putEntryHourLabel.setMinimumSize(QtCore.QSize(130, 30))
        self.putEntryHourLabel.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.putEntryHourLabel.setFont(font)
        self.putEntryHourLabel.setStyleSheet("QLabel {\n"
                                             "    border: 2px rounded;\n"
                                             "    border-color: rgb(57, 57, 57);\n"
                                             "    border-radius: 8px;\n"
                                             "    border-style: outset;\n"
                                             "    background-color: #ffffff;\n"
                                             "    padding: 3px;\n"
                                             "    color:#000000;}")
        self.putEntryHourLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.putEntryHourLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.putEntryHourLabel.setLineWidth(2)
        self.putEntryHourLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.putEntryHourLabel.setObjectName("putEntryHourLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.putEntryHourLabel)
        self.putExitTimeLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.putExitTimeLabel.sizePolicy().hasHeightForWidth())
        self.putExitTimeLabel.setSizePolicy(sizePolicy)
        self.putExitTimeLabel.setMinimumSize(QtCore.QSize(130, 30))
        self.putExitTimeLabel.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.putExitTimeLabel.setFont(font)
        self.putExitTimeLabel.setStyleSheet("QLabel {\n"
                                            "    border: 2px rounded;\n"
                                            "    border-color: rgb(57, 57, 57);\n"
                                            "    border-radius: 8px;\n"
                                            "    border-style: outset;\n"
                                            "    background-color: #ffffff;\n"
                                            "    padding: 3px;\n"
                                            "    color:#000000;}")
        self.putExitTimeLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.putExitTimeLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.putExitTimeLabel.setLineWidth(2)
        self.putExitTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.putExitTimeLabel.setObjectName("putExitTimeLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.putExitTimeLabel)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_3.setObjectName("formLayout_3")
        self.priceLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.priceLabel.sizePolicy().hasHeightForWidth())
        self.priceLabel.setSizePolicy(sizePolicy)
        self.priceLabel.setMinimumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.priceLabel.setFont(font)
        self.priceLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                      "color:#ffffff;")
        self.priceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.priceLabel.setWordWrap(True)
        self.priceLabel.setObjectName("priceLabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.priceLabel)
        self.payedLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payedLabel.sizePolicy().hasHeightForWidth())
        self.payedLabel.setSizePolicy(sizePolicy)
        self.payedLabel.setMinimumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.payedLabel.setFont(font)
        self.payedLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                      "color:#ffffff;")
        self.payedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.payedLabel.setObjectName("payedLabel")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.payedLabel)
        self.parentIDLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parentIDLabel.sizePolicy().hasHeightForWidth())
        self.parentIDLabel.setSizePolicy(sizePolicy)
        self.parentIDLabel.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.parentIDLabel.setFont(font)
        self.parentIDLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                         "color:#ffffff;")
        self.parentIDLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.parentIDLabel.setObjectName("parentIDLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.parentIDLabel)
        self.parentLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parentLabel.sizePolicy().hasHeightForWidth())
        self.parentLabel.setSizePolicy(sizePolicy)
        self.parentLabel.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.parentLabel.setFont(font)
        self.parentLabel.setStyleSheet("background:rgb(80, 80, 80);\n"
                                       "color:#ffffff;")
        self.parentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.parentLabel.setObjectName("parentLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.parentLabel)
        self.putParentLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.putParentLabel.sizePolicy().hasHeightForWidth())
        self.putParentLabel.setSizePolicy(sizePolicy)
        self.putParentLabel.setMinimumSize(QtCore.QSize(210, 30))
        self.putParentLabel.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.putParentLabel.setFont(font)
        self.putParentLabel.setStyleSheet("QLabel {\n"
                                          "    border: 2px rounded;\n"
                                          "    border-color: rgb(57, 57, 57);\n"
                                          "    border-radius: 8px;\n"
                                          "    border-style: outset;\n"
                                          "    background-color: #ffffff;\n"
                                          "    padding: 3px;\n"
                                          "    color:#000000;}")
        self.putParentLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.putParentLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.putParentLabel.setLineWidth(2)
        self.putParentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.putParentLabel.setObjectName("putParentLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.putParentLabel)
        self.putParentIDLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.putParentIDLabel.sizePolicy().hasHeightForWidth())
        self.putParentIDLabel.setSizePolicy(sizePolicy)
        self.putParentIDLabel.setMinimumSize(QtCore.QSize(130, 30))
        self.putParentIDLabel.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.putParentIDLabel.setFont(font)
        self.putParentIDLabel.setStyleSheet("QLabel {\n"
                                            "    border: 2px rounded;\n"
                                            "    border-color: rgb(57, 57, 57);\n"
                                            "    border-radius: 8px;\n"
                                            "    border-style: outset;\n"
                                            "    background-color: #ffffff;\n"
                                            "    padding: 3px;\n"
                                            "    color:#000000;}")
        self.putParentIDLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.putParentIDLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.putParentIDLabel.setLineWidth(2)
        self.putParentIDLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.putParentIDLabel.setObjectName("putParentIDLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.putParentIDLabel)
        self.putPriceLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.putPriceLabel.sizePolicy().hasHeightForWidth())
        self.putPriceLabel.setSizePolicy(sizePolicy)
        self.putPriceLabel.setMinimumSize(QtCore.QSize(130, 30))
        self.putPriceLabel.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.putPriceLabel.setFont(font)
        self.putPriceLabel.setStyleSheet("QLabel {\n"
                                         "    border: 2px rounded;\n"
                                         "    border-color: rgb(57, 57, 57);\n"
                                         "    border-radius: 8px;\n"
                                         "    border-style: outset;\n"
                                         "    background-color: #ffffff;\n"
                                         "    padding: 3px;\n"
                                         "    color:#000000;}")
        self.putPriceLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.putPriceLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.putPriceLabel.setLineWidth(2)
        self.putPriceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.putPriceLabel.setObjectName("putPriceLabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.putPriceLabel)
        self.putPayedLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.putPayedLabel.sizePolicy().hasHeightForWidth())
        self.putPayedLabel.setSizePolicy(sizePolicy)
        self.putPayedLabel.setMinimumSize(QtCore.QSize(70, 30))
        self.putPayedLabel.setMaximumSize(QtCore.QSize(70, 30))
        self.putPayedLabel.setStyleSheet("QLabel {\n"
                                         "    border: 2px rounded;\n"
                                         "    border-color: rgb(57, 57, 57);\n"
                                         "    border-radius: 8px;\n"
                                         "    border-style: outset;\n"
                                         "    background-color: rgb(119, 191, 65);\n"
                                         "    padding: 5 px;\n"
                                         "}")
        self.putPayedLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.putPayedLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.putPayedLabel.setLineWidth(2)
        self.putPayedLabel.setText("")
        self.putPayedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.putPayedLabel.setObjectName("putPayedLabel")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.putPayedLabel)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.dialogSearchRequestsLayout = QtWidgets.QHBoxLayout()
        self.dialogSearchRequestsLayout.setSpacing(30)
        self.dialogSearchRequestsLayout.setObjectName("dialogSearchRequestsLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dialogSearchRequestsLayout.addItem(spacerItem5)
        self.acceptSearchRequestPushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acceptSearchRequestPushButton.sizePolicy().hasHeightForWidth())
        self.acceptSearchRequestPushButton.setSizePolicy(sizePolicy)
        self.acceptSearchRequestPushButton.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.acceptSearchRequestPushButton.setFont(font)
        self.acceptSearchRequestPushButton.setStyleSheet("QPushButton{\n"
                                                         "    padding: 0px 10px 0px 10px;\n"
                                                         "    background: rgb(163, 111, 61);\n"
                                                         "    color: #232323;\n"
                                                         "    border:1px rounded #232323;\n"
                                                         "    border-radius: 5px;\n"
                                                         "    border-style: outset;\n"
                                                         "}\n"
                                                         "\n"
                                                         "QPushButton:hover {\n"
                                                         "    background: #e0d1bd;\n"
                                                         "    }\n"
                                                         "\n"
                                                         "QPushButton:pressed {\n"
                                                         "    border-style: inset;\n"
                                                         "    background: rgb(214, 218, 218);\n"
                                                         "    }\n"
                                                         "")
        self.acceptSearchRequestPushButton.setObjectName("acceptSearchRequestPushButton")
        self.dialogSearchRequestsLayout.addWidget(self.acceptSearchRequestPushButton)
        self.denySearchRequestPushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.denySearchRequestPushButton.sizePolicy().hasHeightForWidth())
        self.denySearchRequestPushButton.setSizePolicy(sizePolicy)
        self.denySearchRequestPushButton.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.denySearchRequestPushButton.setFont(font)
        self.denySearchRequestPushButton.setStyleSheet("QPushButton{\n"
                                                       "    padding: 0px 10px 0px 10px;\n"
                                                       "    background: rgb(230, 230, 230);\n"
                                                       "    color: #232323;\n"
                                                       "    border:1px rounded #232323;\n"
                                                       "    border-radius: 5px;\n"
                                                       "    border-style: outset;\n"
                                                       "}\n"
                                                       "\n"
                                                       "QPushButton:hover {\n"
                                                       "    background: rgb(255,255,255);\n"
                                                       "    }\n"
                                                       "\n"
                                                       "QPushButton:pressed {\n"
                                                       "    border-style: inset;\n"
                                                       "    background: rgb(214, 218, 218);\n"
                                                       "    }")
        self.denySearchRequestPushButton.setObjectName("denySearchRequestPushButton")
        self.dialogSearchRequestsLayout.addWidget(self.denySearchRequestPushButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dialogSearchRequestsLayout.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.dialogSearchRequestsLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "BUSCAR USUARIOS"))
        self.label.setText(_translate("Form", "BUSCAR USUARIO"))
        self.searchIdentifierLabel.setText(_translate("Form", "IDENTIFICADOR"))
        self.searchLineEdit.setPlaceholderText(_translate("Form", placeholders['PH_SEARCH_RECORD']))
        self.nameLabel.setText(_translate("Form", "Nombre"))
        self.braceletNumLabel.setText(_translate("Form", "Número de manilla"))
        self.putNameLabel.setText(_translate("Form", placeholders['PH_NAME']))
        self.putBraceletNumLabel.setText(_translate("Form", placeholders['PH_BRACELET_NUMBER']))
        self.totalTimeLabel.setText(_translate("Form", "Tiempo"))
        self.addedTimeLabel.setText(_translate("Form", "Tiempo extra"))
        self.entryHourLabel.setText(_translate("Form", "Hora entrada"))
        self.exitTimeLabel.setText(_translate("Form", "Hora estimada de salida"))
        self.putTotalTimeLabel.setText(_translate("Form", placeholders['PH_HOUR']))
        self.putAddedTimeLabel.setText(_translate("Form", placeholders['PH_EXTRA_TIME']))
        self.putEntryHourLabel.setText(_translate("Form", placeholders['PH_HOUR']))
        self.putExitTimeLabel.setText(_translate("Form", placeholders['PH_HOUR']))
        self.priceLabel.setText(_translate("Form", "Valor total a pagar"))
        self.payedLabel.setText(_translate("Form", "Cancelado"))
        self.parentIDLabel.setText(_translate("Form", "Acudiente-ID"))
        self.parentLabel.setText(_translate("Form", "Acudiente"))
        self.putParentLabel.setText(_translate("Form", placeholders['PH_PARENT']))
        self.putParentIDLabel.setText(_translate("Form", placeholders['PH_PARENT_ID']))
        self.putPriceLabel.setText(_translate("Form", placeholders['PH_TOTAL_MONEY']))
        self.acceptSearchRequestPushButton.setText(_translate("Form", "Aceptar"))
        self.denySearchRequestPushButton.setText(_translate("Form", "Cancelar"))

    def showSearch(self):
        self.searchWidgetInstance = QtWidgets.QWidget()
        # self.registerWidgetInstance.setWindowIcon(QtGui.QIcon(":/images/fact.png"))
        self.setupUi(self.searchWidgetInstance)
        self.searchWidgetInstance.show()
